cubes:
  - name: td_pagamento_retorno_status
    sql_table: "\"NOTA_MINEIRA_ARM\".\"TD_PAGAMENTO_RETORNO_STATUS\""
    data_source: default

    joins: []

    dimensions:
      - name: sk_pagamento_retorno_status
        sql: '{CUBE}."SK_PAGAMENTO_RETORNO_STATUS"'
        type: number
        primary_key: true

      - name: ds_pagamento_retorno_status
        title: Status de retorno de pagamento
        sql: '{CUBE}."DS_PAGAMENTO_RETORNO_STATUS"'
        type: string
        primary_key: false

    measures:
      - name: count
        title: Contagem
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

    title: Status de retorno de pagamento
    hierarchies: []

views:
  - name: td_pagamento_retorno_status_multifato
    cubes:
      - join_path: tf_requisicao_pagamento_entidade
        prefix: true
        includes: '*'

      - join_path: tf_requisicao_pagamento_participante
        prefix: true
        includes: '*'

      - join_path: td_pagamento_retorno_status
        includes: '*'
