cubes:
  - name: td_sorteio_tipo
    sql_table: "\"NOTA_MINEIRA_ARM\".\"TD_SORTEIO_TIPO\""
    data_source: default

    joins: []

    dimensions:
      - name: sk_sorteio_tipo
        sql: '{CUBE}."SK_SORTEIO_TIPO"'
        type: number
        primary_key: true

      - name: ds_sorteio_tipo
        title: Descrição- Tipo de sorteio
        sql: '{CUBE}."DS_SORTEIO_TIPO"'
        type: string
        primary_key: false

    measures:
      - name: count
        title: Contagem
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

    title: Tipo de sorteio
    hierarchies: []

views:
  - name: td_sorteio_tipo_multifato
    cubes:
      - join_path: tf_bilhetagem_resumo
        prefix: true
        includes: '*'

      - join_path: tf_premiacoes_entidades
        prefix: true
        includes: '*'

      - join_path: tf_premiacoes_participantes
        prefix: true
        includes: '*'

      - join_path: tf_quantidade_bilhetes_participante
        prefix: true
        includes: '*'

      - join_path: td_bilhetagem
        includes:
          - dt_gerar_bilhete
          - dt_inicio_ref_compra
          - dt_fim_ref_compra

      - join_path: td_sorteio_tipo
        includes:
          - ds_sorteio_tipo
