export const SCHEMA_PROPERTY_LABELS: Record<string, string> = {
  hierarchies: 'Hierarquias',
  name: 'Nome',
  sql: 'SQL',
  latitude: 'Latitude',
  longitude: 'Longitude',
  sql_table: 'Tabela SQL',
  extends: 'Herda de',
  data_source: 'Fonte de dados',
  public: 'Público',
  shown: 'Exibido',
  title: 'Título',
  description: 'Descrição',
  type: 'Tipo',
  format: 'Formato',
  meta: 'Metadados',
  refresh_key: 'Chave de atualização',
  cubes: 'Cubos',
  joins: 'Junções',
  dimensions: 'Dimensões',
  measures: 'Medidas',
  segments: 'Segmentos',
  pre_aggregations: 'Pré-agregações',
  includes: 'Inclui',
  excludes: 'Exclui',
  relationship: 'Relacionamento',
  primary_key: 'Chave primária',
  case: 'Condição',
  sub_query: 'Subconsulta',
  drill_members: 'Membros de detalhamento',
  rolling_window: 'Janela móvel',
  filters: 'Filtros',
  time_dimension: 'Dimensão temporal',
  granularity: 'Granularidade',
  partition_granularity: 'Granularidade de particionamento',
  external: 'Externa',
  scheduled_refresh: 'Atualização agendada',
  indexes: 'Índices',
  levels: 'Níveis',
};

export const SCHEMA_BOOLEAN_KEYS = new Set([
  'primary_key',
  'public',
  'shown',
  'external',
  'scheduled_refresh',
  'sub_query',
  'propagate_filters_to_sub_query',
]);
